### PR TITLE
feat(component): allow use of existing createForm props

### PR DESCRIPTION
**Pull request by thegamingninja**
Adds the `createdForm` prop to the `Form` component to allow a form to be created outside of the `Form` component, allowing functions like `updateInitialValues` to be used in the root component.

### CODE REVIEW

**Comment by larrybotha** [comment]
Thanks @thegamingninja - LGTM! Once you resolve the conflict we'll be able to merge shortly thereafter.

**Review by larrybotha — APPROVED** [review]

**Comment by thegamingninja** [comment]
No problem, the conflict should be fixed now.

**Comment by larrybotha** [comment]
@thegamingninja whoops - the latest release seems to have introduced _another_ merged conflict :/

**Comment by thegamingninja** [comment]
I updated the `package-lock.json` again to resolve the conflict, and the Travis CI checks seem to have failed. All the tests passed, and it built without any issues locally.

**Comment by larrybotha** [comment]
@thegamingninja thanks, I'll investigate.

**Comment by larrybotha** [comment]
@thegamingninja so what _may_ be happening is that Svelte doesn't hoist values, so `initialValues` is invalid to reference before `createdForm`. Moving `createdForm` below the values it depends on may fix the error in Travis. I'm not sure why your tests would pass locally, but not on Travis.

Furthermore, what you're sharing with the root component is essentially the context, so instead of `createdForm` perhaps something like `context` would make for a better name. `setContext` should likely contain all the properties from `context`, so you can spread whatever hasn't been explicitly destructured. e.g.

```svelte
// export context as a readonly prop
export const context = createForm({...})

setContext(context);
```

**Comment by thegamingninja** [comment]
I renamed `createdForm` to `context`, and moved it below the prop declarations and it seems to have passed successfully.

Also just wanted to mention, the reason context isn't read-only is to allow for an existing context to be passed in, so I can just call `createForm` in my root component, and pass a context to the `Form` component, instead of having `initialValues` and `validationSchemea` objects that are passed into the `Form` component, and binding to the context of the `Form` component to get access to functions like `updateInitialValues`.

**Comment by larrybotha** [comment]
@thegamingninja see here with some changes I've made to the form component: https://github.com/tjinauyeung/svelte-forms-lib/pull/100/files

Most of the properties are already exposed via slot props, so I've exposed the newer methods that weren't exposed.

Does this address your original PR?

If so, does it help with what you mentioned in https://github.com/tjinauyeung/svelte-forms-lib/pull/93#issuecomment-779485218? If not, we should likely consider that for a separate feature.

**Comment by thegamingninja** [comment]
Yes, the changes do address my original PR and the comment.

Looking back at the PR and my comment, I didn't do a great job explaining the changes, so I'll just give a quick example and compare it to the recent changes. 

I personally think the original PR is slightly cleaner to use, but both solutions allow the use of `updateInitialValues` so either solves the problem. 

Thank you for spending the time working on this PR!

The solution using my PR:
```html
<script>
  import { Form, Field, ErrorMessage, createForm } from 'svelte-forms-lib';

  const nameFormContext = createForm({
    initialValues: {
      firstName: 'Example',
      lastName: 'Person'
    },
    onSubmit: (values) => {
      console.log(values);

      nameFormContext.updateInitialValues(values);
    }
  });
</script>

<Form context={nameFormContext}>
  <label for="firstName">First Name</label>
  <Field type="text" name="firstName" />
  <ErrorMessage name="firstName" />

  <label for="lastName">Last Name</label>
  <Field type="text" name="lastName" />
  <ErrorMessage name="lastName" />

  <button type="submit">Submit</button>
</Form>
```

The solution using the recent changes:
```html
<script>
  import { Form, Field, ErrorMessage } from 'svelte-forms-lib';

  let updateInitialValues;
  const nameFormProps = {
    initialValues: {
      firstName: 'Example',
      lastName: 'Person'
    },
    onSubmit: (values) => {
      console.log(values);

      updateInitialValues(values)
    }
  }
</script>

<Form {...nameFormProps} let:updateInitialValues={updateInitialValues}>
  <label for="firstName">First Name</label>
  <Field type="text" name="firstName" />
  <ErrorMessage name="firstName" />

  <label for="lastName">Last Name</label>
  <Field type="text" name="lastName" />
  <ErrorMessage name="lastName" />

  <button type="submit">Submit</button>
</Form>
```

**Comment by larrybotha** [comment]
@thegamingninja oh, ok, I see now! Your example makes it much clearer now.

Ok, ye, so allowing a user to pass in the form context externally, and internally falling back to the components own call to `createForm` if no context is provided.

This would actually provide a workaround for #56.

I'm gonna close this PR, but I've opened #101 to address passing the context in as a prop.

**Comment by larrybotha** [comment]
@thegamingninja I probably prematurely closed this PR :P 

I'll reopen your PR if you want to add this feature. We'll need you to extend the tests with checks for both the default internal context, and the external user context. It should be a matter of wrapping the tests in a `describe.each` block with the relevant parameters (see the tests for `Form` if you'd like an example of parameterised tests).

This PR feels like this is a moving target with all of my requests and the merge conflicts, and that I keep messing you around, so let me know if you're up for it, otherwise I'll tackle it :)

**Comment by thegamingninja** [comment]
I'm not too familiar with writing tests, so I'll just let you handle that in the other PR to make everything consistent. Thanks for taking the time to work on this!

**Comment by larrybotha** [comment]
@thegamingninja ok cool, no problem. Thanks for your PR and the feedback!

**Comment by larrybotha** [comment]
@thegamingninja you can now pass context in as per #102

**Comment by thegamingninja** [comment]
@larrybotha Awesome. Thank you for working with me to get this added!

**Pull request closed without merging**
