### PR TITLE
docs(licence): add MIT licence - closes #32

### LINKED ISSUE #32: Add license text
**Is your feature request related to a problem? Please describe.**
While the documentation mentions this project is released under an MIT-style license, there is no license text provided anywhere in the codebase. As such I cannot check the license terms

**Describe the solution you'd like**
Provide a LICENSE.md or LICENSE.txt file

### PR DESCRIPTION
**Pull request by larrybotha**
@tjinauyeung not sure what protocol you'd like for PRs, but since your name is in this licence I thought I'd add you as a reviewer.

### CODE REVIEW

**Comment by tjinauyeung** [comment]
Feel free to merge simple PRs like these and publish as well!

**Comment by tjinauyeung** [comment]
If I'm getting around to it I want to install something like https://github.com/all-contributors to give credit to all contributors of this project. For now, thanks for contributing.

**Comment by larrybotha** [comment]
@tjinauyeung ye, wasn't sure about merging this one as your name is in the license, so I'd thought I'd give you a heads up first :)

For publishing I believe you'll need to add me as a maintainer on npm - I have the same username there as here.

From there I can start looking at CI and automated semantic versioning - not sure how `semantic-release` works on projects that already have releases, but it's time I learned!

**Pull request merged**
